modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/MineSE-Project/MineSE-Mod/issues"
license = "GPL3.0"

[[mods]]
modId = "mine_se"
version = "${version}"
displayName = "MineSE"
authors = "wellcoming"
description = '''
A gRPC API to control Minecraft Client
'''
#logoFile = ""

[[dependencies.mine_se]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mine_se]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mine_se]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mine_se.mixins.json"
